<?php
/**
 * @file
 * computed field to display 'Open' or 'Closed'
 */

/**
 * [computed_field_field_dh_class_compute description]
 * @param  [type] &$entity_field [description]
 * @param  [type] $entity_type   [description]
 * @param  [type] $entity        [description]
 * @param  [type] $field         [description]
 * @param  [type] $instance      [description]
 * @param  [type] $langcode      [description]
 * @param  [type] $items         [description]
 * @return [type]                [description]
 */
function computed_field_field_dh_class_compute(&$entity_field, $entity_type, $entity, $field, $instance, $langcode, $items) {

}
