<?php
/**
 * @file
 * computed field to display 'Open' or 'Closed'
 */

/**
 * [computed_field_field_dh_class_compute description]
 * @param  [type] &$entity_field [description]
 * @param  [type] $entity_type   [description]
 * @param  [type] $entity        [description]
 * @param  [type] $field         [description]
 * @param  [type] $instance      [description]
 * @param  [type] $langcode      [description]
 * @param  [type] $items         [description]
 * @return [type]                [description]
 */
function computed_field_field_dh_class_compute(&$entity_field, $entity_type, $entity, $field, $instance, $langcode, $items) {
  $test_field = variable_get('libcal_hours_open_currently_field', 'field_dh_currently_open');
  $test = field_get_items($entity_type, $entity, $test_field);
  $old_class = field_get_items($entity_type, $entity, 'field_dh_class');
  $class = $test[0]['value'] ? 'label-success' : 'label-danger';
  $entity_field[0]['value'] = "$class";
  
  if ($old_class && $old_class[0]['value'] != $class) {
    $is_open = $test[0]['value'] ? 'Open' : 'Closed';
    $location = $entity->title;
    watchdog('libcal_hours_open', 'LibCal shows @open for @loc (field @fld) ', array('@fld' => $test_field, '@open' => $is_open, '@loc' => $location), WATCHDOG_NOTICE);
  }
}


/**
 * display code for computed field
 * @param  [type] $field             [description]
 * @param  [type] $entity_field_item [description]
 * @param  [type] $entity_lang       [description]
 * @param  [type] $langcode          [description]
 * @param  [type] $entity            [description]
 * @return [type]                    [description]
 */
function computed_field_field_dh_class_display($field, $entity_field_item, $entity_lang, $langcode, $entity) {
  return $entity_field_item['value'];
}
